### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gempir** [PatrickRorth/Twitch.TV#9]
Under which license is this project published?

Thanks :)

**Comment by PatrickRorth** [comment]
MIT - i think its called.
Altho, use it as you like, but credit is appriciated :)

**Comment by gempir** [comment]
It's usual to put a LICENSE file in the root of the project, but thanks for the info

**Comment by PatrickRorth** [comment]
Yeah i know, but im not sure what licens its under, so i just didnt made one. But its free for all to use as they like :)

**Comment by gempir** [comment]
Here this might be helpful :) http://choosealicense.com/

**Comment by PatrickRorth** [comment]
Ah great! Thanks! :)
